<?php define( 'DB_NAME', 'wordpress_test' );
define( 'DB_USER', 'admin' );
define( 'DB_PASSWORD', 'root' );
define( 'DB_HOST', '127.0.0.1:10004' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );
$table_prefix = 'wptests_';
define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );
define( 'WP_PHP_BINARY', 'php' );
define( 'WPLANG', '' );
