export enum WorkoutEvent {
    FETCH_REQUEST = 'WORKOUT_FETCH_REQUEST',
    FETCH_SUCCESS = 'WORKOUT_FETCH_SUCCESS',
    FETCH_ERROR = 'WORKOUT_FETCH_ERROR',
    GENERATE_REQUEST = 'WORKOUT_GENERATE_REQUEST',
    GENERATE_SUCCESS = 'WORKOUT_GENERATE_SUCCESS',
    GENERATE_ERROR = 'WORKOUT_GENERATE_ERROR',
    UPDATE_REQUEST = 'WORKOUT_UPDATE_REQUEST',
    UPDATE_SUCCESS = 'WORKOUT_UPDATE_SUCCESS',
    UPDATE_ERROR = 'WORKOUT_UPDATE_ERROR'
} 